export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_EDIT_INFO = 'USER_EDIT_INFO';

export const LABEL_LIST_REQUEST = 'LABEL_LIST_REQUEST';
export const LABEL_LIST_FAIL = 'LABEL_LIST_FAIL';
export const LABEL_LIST_SUCCESS = 'LABEL_LIST_SUCCESS';
export const LABEL_EDIT_INFO = 'LABEL_EDIT_INFO';

export const CONTENT_LIST_REQUEST = 'CONTENT_LIST_REQUEST';
export const CONTENT_LIST_FAIL = 'CONTENT_LIST_FAIL';
export const CONTENT_LIST_SUCCESS = 'CONTENT_LIST_SUCCESS';
export const CONTENT_EDIT_INFO = 'CONTENT_EDIT_INFO';
export const CONTENT_LABEL_LIST = 'CONTENT_LABEL_LIST';
